-- HN stories
ALTER TABLE hn_stories ADD COLUMN IF NOT EXISTS prev_points INT DEFAULT NULL;
ALTER TABLE hn_stories ADD COLUMN IF NOT EXISTS prev_comment_count INT DEFAULT NULL;
ALTER TABLE hn_stories ADD COLUMN IF NOT EXISTS points_velocity REAL DEFAULT NULL;
ALTER TABLE hn_stories ADD COLUMN IF NOT EXISTS comments_velocity REAL DEFAULT NULL;

-- Reddit posts
ALTER TABLE reddit_posts ADD COLUMN IF NOT EXISTS prev_score INT DEFAULT NULL;
ALTER TABLE reddit_posts ADD COLUMN IF NOT EXISTS prev_num_comments INT DEFAULT NULL;
ALTER TABLE reddit_posts ADD COLUMN IF NOT EXISTS score_velocity REAL DEFAULT NULL;
ALTER TABLE reddit_posts ADD COLUMN IF NOT EXISTS comments_velocity REAL DEFAULT NULL;

-- GitHub repos
ALTER TABLE github_repos ADD COLUMN IF NOT EXISTS prev_stars INT DEFAULT NULL;
ALTER TABLE github_repos ADD COLUMN IF NOT EXISTS prev_forks INT DEFAULT NULL;
ALTER TABLE github_repos ADD COLUMN IF NOT EXISTS stars_velocity REAL DEFAULT NULL;

-- X tweets
ALTER TABLE x_scraped_tweets ADD COLUMN IF NOT EXISTS prev_likes INT DEFAULT NULL;
ALTER TABLE x_scraped_tweets ADD COLUMN IF NOT EXISTS prev_retweets INT DEFAULT NULL;
ALTER TABLE x_scraped_tweets ADD COLUMN IF NOT EXISTS prev_views BIGINT DEFAULT NULL;
ALTER TABLE x_scraped_tweets ADD COLUMN IF NOT EXISTS likes_velocity REAL DEFAULT NULL;
ALTER TABLE x_scraped_tweets ADD COLUMN IF NOT EXISTS views_velocity REAL DEFAULT NULL;
